### ISSUE TITLE
fabric plz

### ISSUE THREAD

**Issue by fulide** [zxy19/battery_shield#1]
fabric有希望吗

**Comment by zxy19** [comment]
开发者是学forge的，目前暂时不考虑移植Fabric。目前没有这个能力也没有这个精力。
如果有人能够提出帮助设计开发Fabric版本的，可以联系我。

Forge is primary mod loader that the developer using and it's not considered about migrating this mod to Fabric. I have neither such ability nor so many time.
If anybody volunteers to help with build a fabric version, contact me.
